<?php
/**
 * @file
 * Example module "Progress bar".
 */

/**
 * Implements hook_menu().
 */
function example_progressbar_menu() {
  $items = array();

  $items['examples/ajax_example/progressbar'] = array(
    'title' => 'Progress bar example',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('example_progressbar_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['examples/ajax_example/progressbar/progress/%'] = array(
    'title' => 'Progress bar progress',
    'page callback' => 'example_progressbar_progress',
    'page arguments' => array(4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_FORMID().
 */
function example_progressbar_form($form, &$form_state) {
  $form_state['time'] = REQUEST_TIME;

  $form['status'] = array(
    '#markup' => '<div id="progress-status"></div>',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#ajax' => array(
      'callback' => 'example_progressbar_callback',
      'wrapper' => 'progress-form',
      'progress' => array(
        'type' => 'bar',
        'message' => t('Execute..'),
        'url' => url('examples/ajax_example/progressbar/progress/' . $form_state['time']),
        'interval' => 1000,
      ),
    ),
  );

   return $form;
}

/**
 * Get status progress execute.
 *
 * @param int $time
 *   Timestamp.
 */
function example_progressbar_progress($time) {
  $progress = array(
    'message' => t('Starting execute...'),
    'percentage' => -1,
  );

  $completed_percentage = variable_get('example_progressbar_' . $time, 0);

  if ($completed_percentage) {
    $progress['message'] = t('Executing...');
    $progress['percentage'] = $completed_percentage;
  }

  drupal_json_output($progress);
}

/**
 * Implements hook_FORMID_submit().
 */
function example_progressbar_callback($form, &$form_state) {
  $variable_name = 'example_progressbar_' . $form_state['time'];
  $commands = array();

  variable_set($variable_name, 10);
  sleep(2);
  variable_set($variable_name, 40);
  sleep(2);
  variable_set($variable_name, 70);
  sleep(2);
  variable_set($variable_name, 90);
  sleep(2);
  variable_del($variable_name);

  $commands[] = ajax_command_html('#progress-status', t('Executed.'));

  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}
